module.exports = {
  SECRET: "SECRET",
  EXPIRES_IN: 60 * 60 * 60,

  IMAGE_PATH: "public/images",
  DOCUMENT_PATH: "public/documents",
  SALT: 12,
  LIMIT_SIZE_FILE_UPLOAD: 50 * 1024 * 1024,
  MAXIMUM_NUMBER_FILE_UPLOAD: 5,
  PAGENUM_DEFAULT: 0,
  OFFSET_DEFAULT: 0,
  PAGESIZE_DEFAULT: 10,
  PREFIX_NAMESPACE: "cam"
};
